name: data_testing_for_hb
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0
  path_provider: ^2.0.11


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
